### ISSUE TITLE
Not able to render on react page

### ISSUE THREAD

**Issue by tenze** [tenze/newsapi#1]
I am not able to render the api on my react page. It is not to grabbing the the getAllNews() function.
--App.jsx--

<img width="553" alt="screen shot 2016-12-12 at 2 20 59 pm" src="https://cloud.githubusercontent.com/assets/22038709/21113109/48dcf44e-c076-11e6-8cbf-c2f29a3770b0.png">

---NewsList---

<img width="546" alt="screen shot 2016-12-12 at 2 22 53 pm" src="https://cloud.githubusercontent.com/assets/22038709/21113179/87a4a7c6-c076-11e6-9454-a0979a87f01f.png">

---NewsListItem---

<img width="487" alt="screen shot 2016-12-12 at 2 23 39 pm" src="https://cloud.githubusercontent.com/assets/22038709/21113215/a64fe816-c076-11e6-9595-6500fcf67a6b.png">

--Browser---

<img width="1136" alt="screen shot 2016-12-12 at 2 24 48 pm" src="https://cloud.githubusercontent.com/assets/22038709/21113251/c887aa4a-c076-11e6-88e9-1ef6b6959f31.png">
@gittheking @jasonseminara @trevorpreston @rapala61 @irwin

**Comment by gittheking** [comment]
@tenze your `this.getNews()` should be inside of `componentDidMount()`, not `componentWillMount()`. Try that and see if it helps at all.

**Comment by tenze** [comment]
@gittheking  -- Still same bobby, not able to render on page.

<img width="339" alt="screen shot 2016-12-12 at 4 19 54 pm" src="https://cloud.githubusercontent.com/assets/22038709/21117262/e57ae044-c086-11e6-9ac7-820efc6de41c.png">

**Comment by trevorpreston** [comment]
@tenze @gittheking is this still open?

**Comment by tenze** [comment]
@gittheking @jasonseminara @trevorpreston @rapala61 @irwin  - still open trevor -_-

**Comment by trevorpreston** [comment]
got this

**Comment by tenze** [comment]
fixed
